// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpoQdjuEHszv67_kBGX8ym6c5XWH753WA',
    appId: '1:453896355491:web:e6452ca9f8ccc95d83c916',
    messagingSenderId: '453896355491',
    projectId: 'dsis-7ca4c',
    authDomain: 'dsis-7ca4c.firebaseapp.com',
    storageBucket: 'dsis-7ca4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ImXBaVvPxi4bBxmoMnZryboMntnA6Gw',
    appId: '1:453896355491:android:abb1697a0a7ded4683c916',
    messagingSenderId: '453896355491',
    projectId: 'dsis-7ca4c',
    storageBucket: 'dsis-7ca4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSMnXlks7XWmi2RwI-3v8l6ar1T8sz--s',
    appId: '1:453896355491:ios:f4fd568d047a69b183c916',
    messagingSenderId: '453896355491',
    projectId: 'dsis-7ca4c',
    storageBucket: 'dsis-7ca4c.appspot.com',
    iosClientId: '453896355491-maug8cvfrqjdtal2quius0jcbu7cecpf.apps.googleusercontent.com',
    iosBundleId: 'com.bprldr.dsisApp',
  );
}
